<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbm_user extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbm_user_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('tbm_user/tbm_user_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tbm_user_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tbm_user_model->get_by_id($id);
        if ($row) {
            $data = array(
		'ID' => $row->ID,
		'username' => $row->username,
		'password' => $row->password,
		'email' => $row->email,
	    );
            $this->load->view('tbm_user/tbm_user_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbm_user'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('tbm_user/create_action'),
	    'ID' => set_value('ID'),
	    'username' => set_value('username'),
	    'password' => set_value('password'),
	    'email' => set_value('email'),
	);
        $this->load->view('tbm_user/tbm_user_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'username' => $this->input->post('username',TRUE),
		'password' => $this->input->post('password',TRUE),
		'email' => $this->input->post('email',TRUE),
	    );

            $this->Tbm_user_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('tbm_user'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbm_user_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('tbm_user/update_action'),
		'ID' => set_value('ID', $row->ID),
		'username' => set_value('username', $row->username),
		'password' => set_value('password', $row->password),
		'email' => set_value('email', $row->email),
	    );
            $this->load->view('tbm_user/tbm_user_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbm_user'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('ID', TRUE));
        } else {
            $data = array(
		'username' => $this->input->post('username',TRUE),
		'password' => $this->input->post('password',TRUE),
		'email' => $this->input->post('email',TRUE),
	    );

            $this->Tbm_user_model->update($this->input->post('ID', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('tbm_user'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbm_user_model->get_by_id($id);

        if ($row) {
            $this->Tbm_user_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('tbm_user'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbm_user'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('username', 'username', 'trim|required');
	$this->form_validation->set_rules('password', 'password', 'trim|required');
	$this->form_validation->set_rules('email', 'email', 'trim|required');

	$this->form_validation->set_rules('ID', 'ID', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tbm_user.php */
/* Location: ./application/controllers/Tbm_user.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-30 08:52:12 */
/* http://harviacode.com */