<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbm_facilities extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbm_facilities_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('tbm_facilities/tbm_facilities_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tbm_facilities_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tbm_facilities_model->get_by_id($id);
        if ($row) {
            $data = array(
		'ID' => $row->ID,
		'nama' => $row->nama,
		'biaya' => $row->biaya,
	    );
            $this->load->view('tbm_facilities/tbm_facilities_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbm_facilities'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('tbm_facilities/create_action'),
	    'ID' => set_value('ID'),
	    'nama' => set_value('nama'),
	    'biaya' => set_value('biaya'),
	);
        $this->load->view('tbm_facilities/tbm_facilities_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
		'biaya' => $this->input->post('biaya',TRUE),
	    );

            $this->Tbm_facilities_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('tbm_facilities'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbm_facilities_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('tbm_facilities/update_action'),
		'ID' => set_value('ID', $row->ID),
		'nama' => set_value('nama', $row->nama),
		'biaya' => set_value('biaya', $row->biaya),
	    );
            $this->load->view('tbm_facilities/tbm_facilities_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbm_facilities'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('ID', TRUE));
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
		'biaya' => $this->input->post('biaya',TRUE),
	    );

            $this->Tbm_facilities_model->update($this->input->post('ID', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('tbm_facilities'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbm_facilities_model->get_by_id($id);

        if ($row) {
            $this->Tbm_facilities_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('tbm_facilities'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbm_facilities'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama', 'nama', 'trim|required');
	$this->form_validation->set_rules('biaya', 'biaya', 'trim|required|numeric');

	$this->form_validation->set_rules('ID', 'ID', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tbm_facilities.php */
/* Location: ./application/controllers/Tbm_facilities.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-30 08:52:12 */
/* http://harviacode.com */