<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbt_kamar extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbt_kamar_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('tbt_kamar/tbt_kamar_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tbt_kamar_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tbt_kamar_model->get_by_id($id);
        if ($row) {
            $data = array(
		'ID' => $row->ID,
		'id_kamar' => $row->id_kamar,
		'id_facilities' => $row->id_facilities,
	    );
            $this->load->view('tbt_kamar/tbt_kamar_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbt_kamar'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('tbt_kamar/create_action'),
	    'ID' => set_value('ID'),
	    'id_kamar' => set_value('id_kamar'),
	    'id_facilities' => set_value('id_facilities'),
	);
        $this->load->view('tbt_kamar/tbt_kamar_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_kamar' => $this->input->post('id_kamar',TRUE),
		'id_facilities' => $this->input->post('id_facilities',TRUE),
	    );

            $this->Tbt_kamar_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('tbt_kamar'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbt_kamar_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('tbt_kamar/update_action'),
		'ID' => set_value('ID', $row->ID),
		'id_kamar' => set_value('id_kamar', $row->id_kamar),
		'id_facilities' => set_value('id_facilities', $row->id_facilities),
	    );
            $this->load->view('tbt_kamar/tbt_kamar_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbt_kamar'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('ID', TRUE));
        } else {
            $data = array(
		'id_kamar' => $this->input->post('id_kamar',TRUE),
		'id_facilities' => $this->input->post('id_facilities',TRUE),
	    );

            $this->Tbt_kamar_model->update($this->input->post('ID', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('tbt_kamar'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbt_kamar_model->get_by_id($id);

        if ($row) {
            $this->Tbt_kamar_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('tbt_kamar'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbt_kamar'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_kamar', 'id kamar', 'trim|required');
	$this->form_validation->set_rules('id_facilities', 'id facilities', 'trim|required');

	$this->form_validation->set_rules('ID', 'ID', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tbt_kamar.php */
/* Location: ./application/controllers/Tbt_kamar.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-30 08:52:12 */
/* http://harviacode.com */